import Head from 'next/head';
import Header from '../components/header/Header';
import Sidebar from '../components/sidebar/Sidebar';
import Login from '../components/header/Login';
import Feed from '../components/feed/Feed';
import Widgets from '../components/widgets/Widgets';
import { getSession } from 'next-auth/client';
import { db } from '../firebase';



export default function Home({session,posts}) {
  if(!session) {
    return <Login/>
  }
  return (
    <div className='h-screen bg-gray-100 overflow-hidden' >
      <Head>
        <title>Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

           <Header/>

           <main className='flex ' >
              <Sidebar/> 
              <Feed posts={posts} /> 
              <Widgets/>
           </main>
      
    </div>
  )
}





export const getServerSideProps = async (context) => {
     //get the user 
     const session = await getSession(context);

     const posts = await db.collection('posts').orderBy(
       'timestamp' , 'desc'
     ).get();

     const docs = posts.docs.map((post) => ({
       id:post.id,
       ...post.data(),
       timestamp:null
     }))

     return {
       props:{
         session,
         posts:docs
       }
     }
}



// min 3.06 (create Post component)