import Head from 'next/head';
import Header from '../components/header/Header';
import Sidebar from '../components/sidebar/Sidebar';
import Login from '../components/header/Login';
import Feed from '../components/feed/Feed';
import { getSession } from 'next-auth/client';



export default function Home({session}) {
  if(!session) {
    return <Login/>
  }
  return (
    <div className='h-screen bg-gray-100 overflow-hidden' >
      <Head>
        <title>Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

           <Header/>

           <main className='flex ' >
              <Sidebar/> 
              <Feed/> 
             {/* <Widgets/> */}
           </main>
      
    </div>
  )
}





export const getServerSideProps = async (context) => {
     //get the user 
     const session = await getSession(context);

     return {
       props:{
         session
       }
     }
}



// min 2.43.30 (state for image upload)